{{- if .Values.studio.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "laya-decision-studio.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laya-decision-studio.labels" . | nindent 4 }}
spec:
  {{- with .Values.studio.route.host }}
  host: {{ . }}
  {{- end }}
  port:
    targetPort: http
  {{- if .Values.studio.route.tls.enabled }}
  tls:
    termination: {{ .Values.studio.route.tls.termination }}
    {{- with .Values.studio.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ . }}
    {{- end }}
  {{- end }}
  to:
    kind: Service
    name: {{ template "laya-decision-studio.name" . }}
    weight: 100
{{- end }}
