{{- if .Values.studio.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "laya-decision-studio.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laya-decision-studio.labels" . | nindent 4 }}
  {{- with .Values.studio.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
